# hello everyone, its DRAGON hack 1.0, lets test it
# Raid tool by Maple dc: https://discord.gg/75w5fK8
# Raided by Maple https://discord.gg/75w5fK8
from keyboard import *
from time import sleep
import pyautogui as p, pyperclip
import os
import pyfiglet

os.system("echo invite.gg/Maple")
os.system("echo invite.gg/MapleDev")

ascii_banner = pyfiglet.figlet_format("DRAGON   HACK   1.0")
print(ascii_banner)

os.system("echo Ready!")

N = input("1) Clear Line >>> cl\n"
          "2) Spamming >>> s\n")
if N == "cl":
    p = input("Presses: (Only numbers)\n")
    sleep(2)
    p.press("Backspace", presses=p)
if N == "s":
    N = input("Message to spam: \n")
    sleep(2)
def paste(text001: str):
    pyperclip.copy(text001)
    press_and_release('ctrl + v')

paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")
paste(N + "\n")